var searchData=
[
  ['accountalreadylinked',['AccountAlreadyLinked',['../classLeanCloud_1_1AVException.html#a79d7418a12bc72a830bf56a6eae2a811ac43e4408fec49bc607051b18127229b7',1,'LeanCloud::AVException']]],
  ['ackcommand_2ecs',['AckCommand.cs',['../AckCommand_8cs.html',1,'']]],
  ['acl',['ACL',['../classLeanCloud_1_1AVObject.html#a0573014d673ebeaca82faee0e140e7bf',1,'LeanCloud::AVObject']]],
  ['activatedat',['ActivatedAt',['../classLeanCloud_1_1AVLeaderboardArchive.html#a6ac321be08905ebff0a4eeeaba0f45d2',1,'LeanCloud::AVLeaderboardArchive']]],
  ['add',['Add',['../classLeanCloud_1_1Storage_1_1Internal_1_1FlexibleDictionaryWrapper_3_01TOut_00_01TIn_01_4.html#a4fbffe265332f2dedf5ef5b97cf22ee3',1,'LeanCloud.Storage.Internal.FlexibleDictionaryWrapper&lt; TOut, TIn &gt;.Add(string key, TOut value)'],['../classLeanCloud_1_1Storage_1_1Internal_1_1FlexibleDictionaryWrapper_3_01TOut_00_01TIn_01_4.html#a20f894d54f0692785c3cef782fb67311',1,'LeanCloud.Storage.Internal.FlexibleDictionaryWrapper&lt; TOut, TIn &gt;.Add(KeyValuePair&lt; string, TOut &gt; item)'],['../classLeanCloud_1_1Storage_1_1Internal_1_1FlexibleListWrapper_3_01TOut_00_01TIn_01_4.html#aeb2f8d952caacdaf5759f119b03733eb',1,'LeanCloud.Storage.Internal.FlexibleListWrapper&lt; TOut, TIn &gt;.Add()'],['../classLeanCloud_1_1Storage_1_1Internal_1_1SynchronizedEventHandler_3_01T_01_4.html#a69e8fd333df1837c903e5770ba0180b1',1,'LeanCloud.Storage.Internal.SynchronizedEventHandler&lt; T &gt;.Add()'],['../classLeanCloud_1_1AVObject.html#a83ba6c33583fec1987b9398ea10a1d9e',1,'LeanCloud.AVObject.Add()'],['../classLeanCloud_1_1AVRelation_3_01T_01_4.html#a40042dd4a5c3294b729f87b0342c7f43',1,'LeanCloud.AVRelation&lt; T &gt;.Add()'],['../namespaceLeanCloud.html#a882536d2129fe2030e29d3120f158faaaec211f7c20af43e742bf2570c3cb84f9',1,'LeanCloud.Add()'],['../namespaceLeanCloud_1_1Realtime.html#a5a1a5de17aca57df638197ca990d4790aec211f7c20af43e742bf2570c3cb84f9',1,'LeanCloud.Realtime.Add()']]],
  ['addasync',['AddAsync',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IStorageDictionary_3_01TKey_00_01TValue_01_4.html#a24f8676a1c67c6ef5d743cd093230830',1,'LeanCloud::Storage::Internal::IStorageDictionary&lt; TKey, TValue &gt;']]],
  ['additionalhttpheaders',['AdditionalHTTPHeaders',['../structLeanCloud_1_1AVClient_1_1Configuration.html#aebe308994144a6d6ceda3426b201ef35',1,'LeanCloud::AVClient::Configuration']]],
  ['addmember',['AddMember',['../classLeanCloud_1_1Realtime_1_1AVIMConversationBuilder.html#a162e11e426a88536c8575483a2a2a881',1,'LeanCloud::Realtime::AVIMConversationBuilder']]],
  ['addmembers',['AddMembers',['../classLeanCloud_1_1Realtime_1_1AVIMConversationBuilder.html#a0ec3311a4d35837b42fa104e1aa0fbc8',1,'LeanCloud::Realtime::AVIMConversationBuilder']]],
  ['addmembersasync',['AddMembersAsync',['../classLeanCloud_1_1Realtime_1_1AVIMConversation.html#a280c3a3ba7ba473bac0a28ac0630d6da',1,'LeanCloud::Realtime::AVIMConversation']]],
  ['addrangetolist_3c_20t_20_3e',['AddRangeToList&lt; T &gt;',['../classLeanCloud_1_1AVObject.html#a20ce90171976253912f260c5556fdb79',1,'LeanCloud::AVObject']]],
  ['addrangeuniquetolist_3c_20t_20_3e',['AddRangeUniqueToList&lt; T &gt;',['../classLeanCloud_1_1AVObject.html#a6f9842eb18da10f45c1413f09c6be918',1,'LeanCloud::AVObject']]],
  ['addregisterhook',['AddRegisterHook',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IObjectSubclassingController.html#a5702df423531f5e0ff0eb86b9f6bfa6e',1,'LeanCloud::Storage::Internal::IObjectSubclassingController']]],
  ['addtolist',['AddToList',['../classLeanCloud_1_1AVObject.html#a0047038168cc5c0b06ae85df47a28a9c',1,'LeanCloud::AVObject']]],
  ['adduniquetolist',['AddUniqueToList',['../classLeanCloud_1_1AVObject.html#a06b606773339bdd79bc5c3f8c61b4a5e',1,'LeanCloud::AVObject']]],
  ['affectedmembers',['AffectedMembers',['../classLeanCloud_1_1Realtime_1_1AVIMOnMembersChangedEventArgs.html#a7f0ae1de5fd496f3b58e1ed888153794',1,'LeanCloud::Realtime::AVIMOnMembersChangedEventArgs']]],
  ['affectedtype',['AffectedType',['../classLeanCloud_1_1Realtime_1_1AVIMOnMembersChangedEventArgs.html#aaef060b87bf6445d1d3cfb034109aec5',1,'LeanCloud::Realtime::AVIMOnMembersChangedEventArgs']]],
  ['aggregatedstate',['AggregatedState',['../classLeanCloud_1_1Realtime_1_1AVIMConversation_1_1AggregatedState.html',1,'LeanCloud::Realtime::AVIMConversation']]],
  ['amount',['Amount',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVIncrementOperation.html#ae4d051b91430a6319ef510928adebee1',1,'LeanCloud::Storage::Internal::AVIncrementOperation']]],
  ['apiserver',['ApiServer',['../classLeanCloud_1_1Storage_1_1Internal_1_1AppRouterState.html#a340d2a56b2bc832d29fff07f40b94c45',1,'LeanCloud.Storage.Internal.AppRouterState.ApiServer()'],['../structLeanCloud_1_1AVClient_1_1Configuration.html#afdd913404dc47fcefd9f03b0306cc7c1',1,'LeanCloud.AVClient.Configuration.ApiServer()']]],
  ['app_5fnot_5favailable',['APP_NOT_AVAILABLE',['../classLeanCloud_1_1Realtime_1_1AVIMException.html#a57930dcac4736361464b10ea131e2c0ba49a20b917d6113263f596fbfdc57c4ca',1,'LeanCloud::Realtime::AVIMException']]],
  ['app_5fquota_5fexceeded',['APP_QUOTA_EXCEEDED',['../classLeanCloud_1_1Realtime_1_1AVIMException.html#a57930dcac4736361464b10ea131e2c0ba3b6c46fcb7141a6c6dd2c06ac96d3f78',1,'LeanCloud::Realtime::AVIMException']]],
  ['appcode',['AppCode',['../classLeanCloud_1_1Realtime_1_1AVIMException.html#a49eb6a099f3b94434f135b7715f44606',1,'LeanCloud::Realtime::AVIMException']]],
  ['appid',['AppId',['../classLeanCloud_1_1Realtime_1_1Internal_1_1AVIMCommand.html#ad8b6daf7f48bef4a3bd9a978f9e8f5fa',1,'LeanCloud.Realtime.Internal.AVIMCommand.AppId(string appId)'],['../classLeanCloud_1_1Realtime_1_1Internal_1_1AVIMCommand.html#a7c673704fb7710e11ff7ee0b19ed3e3e',1,'LeanCloud.Realtime.Internal.AVIMCommand.appId()']]],
  ['applicationid',['applicationID',['../classLeanCloud_1_1AVInitializeBehaviour.html#a5857fb4fa7c2bc04aa7c968cf62bbcf3',1,'LeanCloud.AVInitializeBehaviour.applicationID()'],['../structLeanCloud_1_1AVClient_1_1Configuration.html#a801fcec8a5a0d9f25e74637b9cd257d6',1,'LeanCloud.AVClient.Configuration.ApplicationId()'],['../structLeanCloud_1_1Realtime_1_1AVRealtime_1_1Configuration.html#ae31ef0eb33f16f436902c23c2ac0ebd8',1,'LeanCloud.Realtime.AVRealtime.Configuration.ApplicationId()']]],
  ['applicationkey',['applicationKey',['../classLeanCloud_1_1AVInitializeBehaviour.html#abecd6b737dbec4fcb0589189092e4487',1,'LeanCloud.AVInitializeBehaviour.applicationKey()'],['../structLeanCloud_1_1AVClient_1_1Configuration.html#ab77c86a7e186a1c5205cb92795c59838',1,'LeanCloud.AVClient.Configuration.ApplicationKey()'],['../structLeanCloud_1_1Realtime_1_1AVRealtime_1_1Configuration.html#ae2d1a2f64390233a2e56b993eb794529',1,'LeanCloud.Realtime.AVRealtime.Configuration.ApplicationKey()']]],
  ['apply',['Apply',['../classLeanCloud_1_1Storage_1_1Internal_1_1MutableObjectState.html#af5811b362fcca8a4c67c9a773e0047c9',1,'LeanCloud.Storage.Internal.MutableObjectState.Apply(IDictionary&lt; string, IAVFieldOperation &gt; operationSet)'],['../classLeanCloud_1_1Storage_1_1Internal_1_1MutableObjectState.html#a961131e8d07c982b30e29b2583c72aa3',1,'LeanCloud.Storage.Internal.MutableObjectState.Apply(IObjectState other)'],['../classLeanCloud_1_1Storage_1_1Internal_1_1AVAddOperation.html#a4f3a0a4bd49f9b3af2776e7c3bc3fcff',1,'LeanCloud.Storage.Internal.AVAddOperation.Apply()'],['../classLeanCloud_1_1Storage_1_1Internal_1_1AVAddUniqueOperation.html#a80fb105cb06d4f3cbaa1ae839f300da5',1,'LeanCloud.Storage.Internal.AVAddUniqueOperation.Apply()'],['../classLeanCloud_1_1Storage_1_1Internal_1_1AVDeleteOperation.html#ae817438935f83e4a63a3aa9b2afa3230',1,'LeanCloud.Storage.Internal.AVDeleteOperation.Apply()'],['../classLeanCloud_1_1Storage_1_1Internal_1_1AVIncrementOperation.html#a4e483dc8822693556ff8f89fc61542bb',1,'LeanCloud.Storage.Internal.AVIncrementOperation.Apply()'],['../classLeanCloud_1_1Storage_1_1Internal_1_1AVRelationOperation.html#ac0fb70bc2f67523d66ecc942ce0bb16d',1,'LeanCloud.Storage.Internal.AVRelationOperation.Apply()'],['../classLeanCloud_1_1Storage_1_1Internal_1_1AVRemoveOperation.html#a86c6534d10e0dd0e9ffa7722e7c6897f',1,'LeanCloud.Storage.Internal.AVRemoveOperation.Apply()'],['../classLeanCloud_1_1Storage_1_1Internal_1_1AVSetOperation.html#aa254ea0feaf9fff5f7a0c8e7f7e84150',1,'LeanCloud.Storage.Internal.AVSetOperation.Apply()'],['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IAVFieldOperation.html#a383cc65a49ce67370b4db99f0c017769',1,'LeanCloud.Storage.Internal.IAVFieldOperation.Apply()']]],
  ['approutercontroller',['AppRouterController',['../classLeanCloud_1_1Storage_1_1Internal_1_1AppRouterController.html',1,'LeanCloud::Storage::Internal']]],
  ['approutercontroller',['AppRouterController',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVPlugins.html#a8358448762205a11cdae0c5a84aee177',1,'LeanCloud.Storage.Internal.AVPlugins.AppRouterController()'],['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IAVCorePlugins.html#a22d6ab2683c0bc2215ce885fc18887f0',1,'LeanCloud.Storage.Internal.IAVCorePlugins.AppRouterController()']]],
  ['approutercontroller_2ecs',['AppRouterController.cs',['../AppRouterController_8cs.html',1,'']]],
  ['approuterstate',['AppRouterState',['../classLeanCloud_1_1Storage_1_1Internal_1_1AppRouterState.html',1,'LeanCloud::Storage::Internal']]],
  ['approuterstate',['AppRouterState',['../classLeanCloud_1_1Storage_1_1Internal_1_1AppRouterState.html#a525f9af93d22b6ae719e71381d52838a',1,'LeanCloud::Storage::Internal::AppRouterState']]],
  ['approuterstate_2ecs',['AppRouterState.cs',['../AppRouterState_8cs.html',1,'']]],
  ['argument',['Argument',['../classLeanCloud_1_1Realtime_1_1Internal_1_1AVIMCommand.html#a94b0e051614b531f2326b9ec6ca7309a',1,'LeanCloud::Realtime::Internal::AVIMCommand']]],
  ['arguments',['arguments',['../classLeanCloud_1_1Realtime_1_1Internal_1_1AVIMCommand.html#ad1ec30c417ebf5a5c3b58e1269a0ed85',1,'LeanCloud::Realtime::Internal::AVIMCommand']]],
  ['as_3c_20t_20_3e',['As&lt; T &gt;',['../classLeanCloud_1_1Utilities_1_1Conversion.html#ace0fd89db480c883113eb5066a713473',1,'LeanCloud::Utilities::Conversion']]],
  ['ascending',['ASCENDING',['../namespaceLeanCloud.html#a4b214e07f71915b0d9376ef4f2e839a0a83ec681a20197326c163ea3b39ef7c32',1,'LeanCloud']]],
  ['asmainaccount',['AsMainAccount',['../classLeanCloud_1_1AVUserAuthDataLogInOption.html#a73dec5bcb4c89cc5b334111a1e04213a',1,'LeanCloud::AVUserAuthDataLogInOption']]],
  ['associateauthdataandunionidasync',['AssociateAuthDataAndUnionIdAsync',['../classLeanCloud_1_1AVUser.html#a1a146f58440e00e680677f40938d5246',1,'LeanCloud::AVUser']]],
  ['associateauthdataasync',['AssociateAuthDataAsync',['../classLeanCloud_1_1AVUser.html#a33b966e9a242c0a3b838d7f2fa95afd1',1,'LeanCloud::AVUser']]],
  ['authenticateasync',['AuthenticateAsync',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IAVAuthenticationProvider.html#ac910ad2947b8e651c917de8bc0b8fbc5',1,'LeanCloud::Storage::Internal::IAVAuthenticationProvider']]],
  ['authtype',['AuthType',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IAVAuthenticationProvider.html#a998e3c90fbbcd7d189c1c754a2dff173',1,'LeanCloud::Storage::Internal::IAVAuthenticationProvider']]],
  ['autoread',['AutoRead',['../structLeanCloud_1_1Realtime_1_1AVIMClient_1_1Configuration.html#add8623a57818b9f75db1a5d31132618e',1,'LeanCloud::Realtime::AVIMClient::Configuration']]],
  ['avacl',['AVACL',['../classLeanCloud_1_1AVACL.html',1,'LeanCloud']]],
  ['avacl',['AVACL',['../classLeanCloud_1_1AVACL.html#aed0e6d65eb774a107a445476f9927942',1,'LeanCloud.AVACL.AVACL()'],['../classLeanCloud_1_1AVACL.html#aabb6ee44333fcabdabf2a9f143ec2019',1,'LeanCloud.AVACL.AVACL(AVUser owner)']]],
  ['avacl_2ecs',['AVACL.cs',['../AVACL_8cs.html',1,'']]],
  ['avaddoperation',['AVAddOperation',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVAddOperation.html#a9f8a2eb788276421a65ca9d9fab266f2',1,'LeanCloud::Storage::Internal::AVAddOperation']]],
  ['avaddoperation',['AVAddOperation',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVAddOperation.html',1,'LeanCloud::Storage::Internal']]],
  ['avaddoperation_2ecs',['AVAddOperation.cs',['../AVAddOperation_8cs.html',1,'']]],
  ['avadduniqueoperation',['AVAddUniqueOperation',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVAddUniqueOperation.html#acd5a234fdde1b79207683c47d8429b80',1,'LeanCloud::Storage::Internal::AVAddUniqueOperation']]],
  ['avadduniqueoperation',['AVAddUniqueOperation',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVAddUniqueOperation.html',1,'LeanCloud::Storage::Internal']]],
  ['avadduniqueoperation_2ecs',['AVAddUniqueOperation.cs',['../AVAddUniqueOperation_8cs.html',1,'']]],
  ['avclassnameattribute',['AVClassNameAttribute',['../classLeanCloud_1_1AVClassNameAttribute.html#a20d14e5ed5b55d109e73eb7363a5392b',1,'LeanCloud::AVClassNameAttribute']]],
  ['avclassnameattribute',['AVClassNameAttribute',['../classLeanCloud_1_1AVClassNameAttribute.html',1,'LeanCloud']]],
  ['avclassnameattribute_2ecs',['AVClassNameAttribute.cs',['../AVClassNameAttribute_8cs.html',1,'']]],
  ['avclient',['AVClient',['../classLeanCloud_1_1AVClient.html',1,'LeanCloud']]],
  ['avclient_2ecs',['AVClient.cs',['../AVClient_8cs.html',1,'']]],
  ['avcloud',['AVCloud',['../classLeanCloud_1_1AVCloud.html',1,'LeanCloud']]],
  ['avcloud_2ecs',['AVCloud.cs',['../AVCloud_8cs.html',1,'']]],
  ['avcloudcodecontroller',['AVCloudCodeController',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVCloudCodeController.html#ac7546ccb3fb69535888fa1e268e89f24',1,'LeanCloud::Storage::Internal::AVCloudCodeController']]],
  ['avcloudcodecontroller',['AVCloudCodeController',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVCloudCodeController.html',1,'LeanCloud::Storage::Internal']]],
  ['avcloudcodecontroller_2ecs',['AVCloudCodeController.cs',['../AVCloudCodeController_8cs.html',1,'']]],
  ['avcommand',['AVCommand',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVCommand.html#a1cfc7494b55b757e2ec1a3eaffb7e0c7',1,'LeanCloud.Storage.Internal.AVCommand.AVCommand(string relativeUri, string method, string sessionToken=null, IList&lt; KeyValuePair&lt; string, string &gt;&gt; headers=null, IDictionary&lt; string, object &gt; data=null)'],['../classLeanCloud_1_1Storage_1_1Internal_1_1AVCommand.html#a0d352a36bd1373667c3d6107a0f7af84',1,'LeanCloud.Storage.Internal.AVCommand.AVCommand(string relativeUri, string method, string sessionToken=null, IList&lt; KeyValuePair&lt; string, string &gt;&gt; headers=null, Stream stream=null, string contentType=null)'],['../classLeanCloud_1_1Storage_1_1Internal_1_1AVCommand.html#a6aa206faadac071a4393dbd8b9e787c8',1,'LeanCloud.Storage.Internal.AVCommand.AVCommand(AVCommand other)']]],
  ['avcommand',['AVCommand',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVCommand.html',1,'LeanCloud::Storage::Internal']]],
  ['avcommand_2ecs',['AVCommand.cs',['../AVCommand_8cs.html',1,'']]],
  ['avcommandrunner',['AVCommandRunner',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVCommandRunner.html#a949255e39d778a6efea7bbb986b69680',1,'LeanCloud::Storage::Internal::AVCommandRunner']]],
  ['avcommandrunner',['AVCommandRunner',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVCommandRunner.html',1,'LeanCloud::Storage::Internal']]],
  ['avcommandrunner_2ecs',['AVCommandRunner.cs',['../AVCommandRunner_8cs.html',1,'']]],
  ['avconfig',['AVConfig',['../classLeanCloud_1_1AVConfig.html',1,'LeanCloud']]],
  ['avconfig_2ecs',['AVConfig.cs',['../AVConfig_8cs.html',1,'']]],
  ['avconfigcontroller_2ecs',['AVConfigController.cs',['../AVConfigController_8cs.html',1,'']]],
  ['avconfigextensions',['AVConfigExtensions',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVConfigExtensions.html',1,'LeanCloud::Storage::Internal']]],
  ['avconfigextensions_2ecs',['AVConfigExtensions.cs',['../AVConfigExtensions_8cs.html',1,'']]],
  ['avcoreextensions',['AVCoreExtensions',['../classLeanCloud_1_1AVCoreExtensions.html',1,'LeanCloud']]],
  ['avcoreplugins_2ecs',['AVCorePlugins.cs',['../AVCorePlugins_8cs.html',1,'']]],
  ['avcurrentconfigcontroller_2ecs',['AVCurrentConfigController.cs',['../AVCurrentConfigController_8cs.html',1,'']]],
  ['avcurrentusercontroller',['AVCurrentUserController',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVCurrentUserController.html',1,'LeanCloud::Storage::Internal']]],
  ['avcurrentusercontroller',['AVCurrentUserController',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVCurrentUserController.html#aa601faa400ef363d2852020fcc5506f5',1,'LeanCloud::Storage::Internal::AVCurrentUserController']]],
  ['avcurrentusercontroller_2ecs',['AVCurrentUserController.cs',['../AVCurrentUserController_8cs.html',1,'']]],
  ['avdecoder',['AVDecoder',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVDecoder.html',1,'LeanCloud::Storage::Internal']]],
  ['avdecoder_2ecs',['AVDecoder.cs',['../AVDecoder_8cs.html',1,'']]],
  ['avdeleteoperation',['AVDeleteOperation',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVDeleteOperation.html',1,'LeanCloud::Storage::Internal']]],
  ['avdeleteoperation_2ecs',['AVDeleteOperation.cs',['../AVDeleteOperation_8cs.html',1,'']]],
  ['avdownloadprogresseventargs',['AVDownloadProgressEventArgs',['../classLeanCloud_1_1AVDownloadProgressEventArgs.html#af500990c64bad5097f3b0f2d69169412',1,'LeanCloud::AVDownloadProgressEventArgs']]],
  ['avdownloadprogresseventargs',['AVDownloadProgressEventArgs',['../classLeanCloud_1_1AVDownloadProgressEventArgs.html',1,'LeanCloud']]],
  ['avdownloadprogresseventargs_2ecs',['AVDownloadProgressEventArgs.cs',['../AVDownloadProgressEventArgs_8cs.html',1,'']]],
  ['avencoder',['AVEncoder',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVEncoder.html',1,'LeanCloud::Storage::Internal']]],
  ['avencoder_2ecs',['AVEncoder.cs',['../AVEncoder_8cs.html',1,'']]],
  ['avexception',['AVException',['../classLeanCloud_1_1AVException.html',1,'LeanCloud']]],
  ['avexception_2ecs',['AVException.cs',['../AVException_8cs.html',1,'']]],
  ['avextensions',['AVExtensions',['../classLeanCloud_1_1AVExtensions.html',1,'LeanCloud']]],
  ['avextensions_2ecs',['AVExtensions.cs',['../AVExtensions_8cs.html',1,'']]],
  ['avfieldnameattribute',['AVFieldNameAttribute',['../classLeanCloud_1_1AVFieldNameAttribute.html#ad3641e06bfdd8d7627ef1ad4fb50eae1',1,'LeanCloud::AVFieldNameAttribute']]],
  ['avfieldnameattribute',['AVFieldNameAttribute',['../classLeanCloud_1_1AVFieldNameAttribute.html',1,'LeanCloud']]],
  ['avfieldnameattribute_2ecs',['AVFieldNameAttribute.cs',['../AVFieldNameAttribute_8cs.html',1,'']]],
  ['avfieldoperations',['AVFieldOperations',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVFieldOperations.html',1,'LeanCloud::Storage::Internal']]],
  ['avfieldoperations_2ecs',['AVFieldOperations.cs',['../AVFieldOperations_8cs.html',1,'']]],
  ['avfile',['AVFile',['../classLeanCloud_1_1AVFile.html#a58e3c5c29f93b3006b107e0876fb0312',1,'LeanCloud.AVFile.AVFile(string name, Stream data, string mimeType=null, IDictionary&lt; string, object &gt; metaData=null)'],['../classLeanCloud_1_1AVFile.html#ac8d2361e6cc6dfd3c96c12a71bdfb4b9',1,'LeanCloud.AVFile.AVFile(string name, byte[] data, string mimeType=null)'],['../classLeanCloud_1_1AVFile.html#a2df9ebb463754b9eb91925f7b31169d0',1,'LeanCloud.AVFile.AVFile(string name, Stream data, string mimeType=null)'],['../classLeanCloud_1_1AVFile.html#ad74cc310c1567334922ac8dfa3b4c7ae',1,'LeanCloud.AVFile.AVFile(string name, byte[] data)'],['../classLeanCloud_1_1AVFile.html#a43ce4c1394aae4030f6c836678ce5ce8',1,'LeanCloud.AVFile.AVFile(string name, byte[] data, IDictionary&lt; string, object &gt; metaData)'],['../classLeanCloud_1_1AVFile.html#a0b0da8cfd72607ea6e06e1c43d9e3a5f',1,'LeanCloud.AVFile.AVFile(string name, Stream data, IDictionary&lt; string, object &gt; metaData)'],['../classLeanCloud_1_1AVFile.html#a7e7d3b5079dab55692b8f8f7c50b954c',1,'LeanCloud.AVFile.AVFile(string name, Stream data)'],['../classLeanCloud_1_1AVFile.html#a1230191adeb1a8552ec516ce88fd194a',1,'LeanCloud.AVFile.AVFile(string name, Uri uri, string mimeType=null, IDictionary&lt; string, object &gt; metaData=null)'],['../classLeanCloud_1_1AVFile.html#a8f7d715bef5fe48103985dc669897f97',1,'LeanCloud.AVFile.AVFile(string name, string url, string mimeType=null, IDictionary&lt; string, object &gt; metaData=null)'],['../classLeanCloud_1_1AVFile.html#a784b9e328b6bce3bcac9bc9f45924139',1,'LeanCloud.AVFile.AVFile(string name, string url, IDictionary&lt; string, object &gt; metaData)'],['../classLeanCloud_1_1AVFile.html#a02ce73c8c9a90e5886c6ad3c527ccac2',1,'LeanCloud.AVFile.AVFile(string name, Uri uri, string mimeType=null)'],['../classLeanCloud_1_1AVFile.html#a1fcaea8099c387824cad64b54f4ea0b9',1,'LeanCloud.AVFile.AVFile(string name, Uri uri)'],['../classLeanCloud_1_1AVFile.html#aa0bc9f091ec29fbb4933b1de5c1d5647',1,'LeanCloud.AVFile.AVFile(string name, string url)']]],
  ['avfile',['AVFile',['../classLeanCloud_1_1AVFile.html',1,'LeanCloud']]],
  ['avfile_2ecs',['AVFile.cs',['../AVFile_8cs.html',1,'']]],
  ['avfilecontroller',['AVFileController',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVFileController.html#a1eb37c67ea7efb258b03c4774db104c6',1,'LeanCloud::Storage::Internal::AVFileController']]],
  ['avfilecontroller',['AVFileController',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVFileController.html',1,'LeanCloud::Storage::Internal']]],
  ['avfilecontroller_2ecs',['AVFileController.cs',['../AVFileController_8cs.html',1,'']]],
  ['avfileextensions',['AVFileExtensions',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVFileExtensions.html',1,'LeanCloud::Storage::Internal']]],
  ['avfileextensions_2ecs',['AVFileExtensions.cs',['../AVFileExtensions_8cs.html',1,'']]],
  ['avgeodistance',['AVGeoDistance',['../structLeanCloud_1_1AVGeoDistance.html#af6ea6241428972dae55cade74800483a',1,'LeanCloud::AVGeoDistance']]],
  ['avgeodistance',['AVGeoDistance',['../structLeanCloud_1_1AVGeoDistance.html',1,'LeanCloud']]],
  ['avgeodistance_2ecs',['AVGeoDistance.cs',['../AVGeoDistance_8cs.html',1,'']]],
  ['avgeopoint',['AVGeoPoint',['../structLeanCloud_1_1AVGeoPoint.html#adecdd42563b51a87f489abfc5665d3c7',1,'LeanCloud::AVGeoPoint']]],
  ['avgeopoint',['AVGeoPoint',['../structLeanCloud_1_1AVGeoPoint.html',1,'LeanCloud']]],
  ['avgeopoint_2ecs',['AVGeoPoint.cs',['../AVGeoPoint_8cs.html',1,'']]],
  ['avimaudiomessage',['AVIMAudioMessage',['../classLeanCloud_1_1Realtime_1_1AVIMAudioMessage.html',1,'LeanCloud::Realtime']]],
  ['avimaudiomessage_2ecs',['AVIMAudioMessage.cs',['../AVIMAudioMessage_8cs.html',1,'']]],
  ['avimbinarymessage',['AVIMBinaryMessage',['../classLeanCloud_1_1Realtime_1_1AVIMBinaryMessage.html#a5d40d04e9c71f0b5a0d29b132cb68e2a',1,'LeanCloud.Realtime.AVIMBinaryMessage.AVIMBinaryMessage()'],['../classLeanCloud_1_1Realtime_1_1AVIMBinaryMessage.html#af507adc4b92a8921992e8804b3d6a959',1,'LeanCloud.Realtime.AVIMBinaryMessage.AVIMBinaryMessage(byte[] data)']]],
  ['avimbinarymessage',['AVIMBinaryMessage',['../classLeanCloud_1_1Realtime_1_1AVIMBinaryMessage.html',1,'LeanCloud::Realtime']]],
  ['avimbinarymessage_2ecs',['AVIMBinaryMessage.cs',['../AVIMBinaryMessage_8cs.html',1,'']]],
  ['avimclient',['AVIMClient',['../classLeanCloud_1_1Realtime_1_1AVIMClient.html',1,'LeanCloud::Realtime']]],
  ['avimclient_2ecs',['AVIMClient.cs',['../AVIMClient_8cs.html',1,'']]],
  ['avimclientextensions',['AVIMClientExtensions',['../classLeanCloud_1_1Realtime_1_1AVIMClientExtensions.html',1,'LeanCloud::Realtime']]],
  ['avimcommand',['AVIMCommand',['../classLeanCloud_1_1Realtime_1_1Internal_1_1AVIMCommand.html',1,'LeanCloud::Realtime::Internal']]],
  ['avimcommand',['AVIMCommand',['../classLeanCloud_1_1Realtime_1_1Internal_1_1AVIMCommand.html#a52879c0e6c171734ffa7c889ba990096',1,'LeanCloud.Realtime.Internal.AVIMCommand.AVIMCommand()'],['../classLeanCloud_1_1Realtime_1_1Internal_1_1AVIMCommand.html#a0b528c555f66d0d391de654c9531bbe2',1,'LeanCloud.Realtime.Internal.AVIMCommand.AVIMCommand(string cmd=null, string op=null, string appId=null, string peerId=null, AVIMSignature signature=null, IDictionary&lt; string, object &gt; arguments=null)'],['../classLeanCloud_1_1Realtime_1_1Internal_1_1AVIMCommand.html#a74dbe0d2001288011e9e3b2b5e7c5dbc',1,'LeanCloud.Realtime.Internal.AVIMCommand.AVIMCommand(AVIMCommand source, string cmd=null, string op=null, string appId=null, string peerId=null, IDictionary&lt; string, object &gt; arguments=null, AVIMSignature signature=null)']]],
  ['avimcommand_2ecs',['AVIMCommand.cs',['../AVIMCommand_8cs.html',1,'']]],
  ['avimcommandrunner',['AVIMCommandRunner',['../classLeanCloud_1_1Realtime_1_1AVRealtime.html#a158b3e25916c7da918c7fa4f2030b333',1,'LeanCloud.Realtime.AVRealtime.AVIMCommandRunner()'],['../classLeanCloud_1_1Realtime_1_1Internal_1_1AVIMCommandRunner.html#a89c6d187606d2727fb8e1195d56d317b',1,'LeanCloud.Realtime.Internal.AVIMCommandRunner.AVIMCommandRunner()']]],
  ['avimcommandrunner',['AVIMCommandRunner',['../classLeanCloud_1_1Realtime_1_1Internal_1_1AVIMCommandRunner.html',1,'LeanCloud::Realtime::Internal']]],
  ['avimcommandrunner_2ecs',['AVIMCommandRunner.cs',['../AVIMCommandRunner_8cs.html',1,'']]],
  ['avimconversation',['AVIMConversation',['../classLeanCloud_1_1Realtime_1_1AVIMConversation.html#a466f57ccc999bf9519e3da6e9fa359f9',1,'LeanCloud.Realtime.AVIMConversation.AVIMConversation(string id)'],['../classLeanCloud_1_1Realtime_1_1AVIMConversation.html#a723b9551ba9e29ff9124556e0d602081',1,'LeanCloud.Realtime.AVIMConversation.AVIMConversation(string id, AVIMClient client)']]],
  ['avimconversation',['AVIMConversation',['../classLeanCloud_1_1Realtime_1_1AVIMConversation.html',1,'LeanCloud::Realtime']]],
  ['avimconversation_2ecs',['AVIMConversation.cs',['../AVIMConversation_8cs.html',1,'']]],
  ['avimconversationbuilder',['AVIMConversationBuilder',['../classLeanCloud_1_1Realtime_1_1AVIMConversationBuilder.html',1,'LeanCloud::Realtime']]],
  ['avimconversationeventtype',['AVIMConversationEventType',['../namespaceLeanCloud_1_1Realtime.html#a5fe8d3aef19c5ab04e8de70bd1b4b31e',1,'LeanCloud::Realtime']]],
  ['avimconversationextensions',['AVIMConversationExtensions',['../classLeanCloud_1_1Realtime_1_1AVIMConversationExtensions.html',1,'LeanCloud::Realtime']]],
  ['avimconversationlistener_2ecs',['AVIMConversationListener.cs',['../AVIMConversationListener_8cs.html',1,'']]],
  ['avimconversationquery',['AVIMConversationQuery',['../classLeanCloud_1_1Realtime_1_1AVIMConversationQuery.html',1,'LeanCloud::Realtime']]],
  ['avimconversationquery_2ecs',['AVIMConversationQuery.cs',['../AVIMConversationQuery_8cs.html',1,'']]],
  ['avimcoreplugins_2ecs',['AVIMCorePlugins.cs',['../AVIMCorePlugins_8cs.html',1,'']]],
  ['avimdisconnecteventargs',['AVIMDisconnectEventArgs',['../classLeanCloud_1_1Realtime_1_1AVIMDisconnectEventArgs.html#a953075f4e7bf3a1bd4882da9f9948ac0',1,'LeanCloud.Realtime.AVIMDisconnectEventArgs.AVIMDisconnectEventArgs()'],['../classLeanCloud_1_1Realtime_1_1AVIMDisconnectEventArgs.html#a6e276e3f8ec69ef5c68df5ee08dc6125',1,'LeanCloud.Realtime.AVIMDisconnectEventArgs.AVIMDisconnectEventArgs(int _code, string _reason, string _detail)']]],
  ['avimdisconnecteventargs',['AVIMDisconnectEventArgs',['../classLeanCloud_1_1Realtime_1_1AVIMDisconnectEventArgs.html',1,'LeanCloud::Realtime']]],
  ['avimenumerator_2ecs',['AVIMEnumerator.cs',['../AVIMEnumerator_8cs.html',1,'']]],
  ['avimeventargs',['AVIMEventArgs',['../classLeanCloud_1_1Realtime_1_1AVIMEventArgs.html',1,'LeanCloud::Realtime']]],
  ['avimeventargs',['AVIMEventArgs',['../classLeanCloud_1_1Realtime_1_1AVIMEventArgs.html#a64110dd87dcaa8a53921c0008738bd70',1,'LeanCloud::Realtime::AVIMEventArgs']]],
  ['avimeventargs_2ecs',['AVIMEventArgs.cs',['../AVIMEventArgs_8cs.html',1,'']]],
  ['avimexception',['AVIMException',['../classLeanCloud_1_1Realtime_1_1AVIMException.html',1,'LeanCloud::Realtime']]],
  ['avimexception_2ecs',['AVIMException.cs',['../AVIMException_8cs.html',1,'']]],
  ['avimfilemessage',['AVIMFileMessage',['../classLeanCloud_1_1Realtime_1_1AVIMFileMessage.html#afd2d8647da064d1661d725ccb7411f33',1,'LeanCloud.Realtime.AVIMFileMessage.AVIMFileMessage()'],['../classLeanCloud_1_1Realtime_1_1AVIMFileMessage.html#aca8603364a8d09cbbbacc9bc9d84577b',1,'LeanCloud.Realtime.AVIMFileMessage.AVIMFileMessage(AVIMTypedMessage message)']]],
  ['avimfilemessage',['AVIMFileMessage',['../classLeanCloud_1_1Realtime_1_1AVIMFileMessage.html',1,'LeanCloud::Realtime']]],
  ['avimimagemessage',['AVIMImageMessage',['../classLeanCloud_1_1Realtime_1_1AVIMImageMessage.html',1,'LeanCloud::Realtime']]],
  ['avimimagemessage_2ecs',['AVIMImageMessage.cs',['../AVIMImageMessage_8cs.html',1,'']]],
  ['aviminvitedlistener',['AVIMInvitedListener',['../classLeanCloud_1_1Realtime_1_1AVIMInvitedListener.html',1,'LeanCloud::Realtime']]],
  ['avimkickedlistener',['AVIMKickedListener',['../classLeanCloud_1_1Realtime_1_1AVIMKickedListener.html',1,'LeanCloud::Realtime']]],
  ['avimlocationmessage',['AVIMLocationMessage',['../classLeanCloud_1_1Realtime_1_1AVIMLocationMessage.html#aa9e5f990a9ab5777e62aded9f8cf1ada',1,'LeanCloud.Realtime.AVIMLocationMessage.AVIMLocationMessage()'],['../classLeanCloud_1_1Realtime_1_1AVIMLocationMessage.html#ac530b00c74345a21381d96b041251aa6',1,'LeanCloud.Realtime.AVIMLocationMessage.AVIMLocationMessage(AVGeoPoint location)']]],
  ['avimlocationmessage',['AVIMLocationMessage',['../classLeanCloud_1_1Realtime_1_1AVIMLocationMessage.html',1,'LeanCloud::Realtime']]],
  ['avimmembersjoinlistener',['AVIMMembersJoinListener',['../classLeanCloud_1_1Realtime_1_1AVIMMembersJoinListener.html',1,'LeanCloud::Realtime']]],
  ['avimmembersleftlistener',['AVIMMembersLeftListener',['../classLeanCloud_1_1Realtime_1_1AVIMMembersLeftListener.html',1,'LeanCloud::Realtime']]],
  ['avimmessage',['AVIMMessage',['../classLeanCloud_1_1Realtime_1_1AVIMMessage.html#a099fcd44d45f9d323a73328b7185c536',1,'LeanCloud::Realtime::AVIMMessage']]],
  ['avimmessage',['AVIMMessage',['../classLeanCloud_1_1Realtime_1_1AVIMMessage.html',1,'LeanCloud::Realtime']]],
  ['avimmessage_2ecs',['AVIMMessage.cs',['../AVIMMessage_8cs.html',1,'']]],
  ['avimmessageclassnameattribute',['AVIMMessageClassNameAttribute',['../classLeanCloud_1_1Realtime_1_1AVIMMessageClassNameAttribute.html#a582827f97503c880bbcc67b3015c1d7f',1,'LeanCloud::Realtime::AVIMMessageClassNameAttribute']]],
  ['avimmessageclassnameattribute',['AVIMMessageClassNameAttribute',['../classLeanCloud_1_1Realtime_1_1AVIMMessageClassNameAttribute.html',1,'LeanCloud::Realtime']]],
  ['avimmessageclassnameattribute_2ecs',['AVIMMessageClassNameAttribute.cs',['../AVIMMessageClassNameAttribute_8cs.html',1,'']]],
  ['avimmessagedecorator',['AVIMMessageDecorator',['../classLeanCloud_1_1Realtime_1_1AVIMMessageDecorator.html#a229abca4f517eda46ac2450403dc19eb',1,'LeanCloud::Realtime::AVIMMessageDecorator']]],
  ['avimmessagedecorator',['AVIMMessageDecorator',['../classLeanCloud_1_1Realtime_1_1AVIMMessageDecorator.html',1,'LeanCloud::Realtime']]],
  ['avimmessageemitterbuilder',['AVIMMessageEmitterBuilder',['../classLeanCloud_1_1Realtime_1_1AVIMMessageEmitterBuilder.html',1,'LeanCloud::Realtime']]],
  ['avimmessageeventargs',['AVIMMessageEventArgs',['../classLeanCloud_1_1Realtime_1_1AVIMMessageEventArgs.html#a375cdc14425511bdf62cac23880941ec',1,'LeanCloud::Realtime::AVIMMessageEventArgs']]],
  ['avimmessageeventargs',['AVIMMessageEventArgs',['../classLeanCloud_1_1Realtime_1_1AVIMMessageEventArgs.html',1,'LeanCloud::Realtime']]],
  ['avimmessagefieldnameattribute',['AVIMMessageFieldNameAttribute',['../classLeanCloud_1_1Realtime_1_1AVIMMessageFieldNameAttribute.html#acbf498abc8338d9783184af51c827505',1,'LeanCloud::Realtime::AVIMMessageFieldNameAttribute']]],
  ['avimmessagefieldnameattribute',['AVIMMessageFieldNameAttribute',['../classLeanCloud_1_1Realtime_1_1AVIMMessageFieldNameAttribute.html',1,'LeanCloud::Realtime']]],
  ['avimmessagefieldnameattribute_2ecs',['AVIMMessageFieldNameAttribute.cs',['../AVIMMessageFieldNameAttribute_8cs.html',1,'']]],
  ['avimmessagelistener',['AVIMMessageListener',['../classLeanCloud_1_1Realtime_1_1AVIMMessageListener.html#a77253f5ac1f042bd066a2da6110ce37d',1,'LeanCloud::Realtime::AVIMMessageListener']]],
  ['avimmessagelistener',['AVIMMessageListener',['../classLeanCloud_1_1Realtime_1_1AVIMMessageListener.html',1,'LeanCloud::Realtime']]],
  ['avimmessagelistener_2ecs',['AVIMMessageListener.cs',['../AVIMMessageListener_8cs.html',1,'']]],
  ['avimmessagepager',['AVIMMessagePager',['../classLeanCloud_1_1Realtime_1_1AVIMMessagePager.html#ab466a90704a4c29b9854f4622381a6b3',1,'LeanCloud::Realtime::AVIMMessagePager']]],
  ['avimmessagepager',['AVIMMessagePager',['../classLeanCloud_1_1Realtime_1_1AVIMMessagePager.html',1,'LeanCloud::Realtime']]],
  ['avimmessagepatcheventargs',['AVIMMessagePatchEventArgs',['../classLeanCloud_1_1Realtime_1_1AVIMMessagePatchEventArgs.html',1,'LeanCloud::Realtime']]],
  ['avimmessagepatcheventargs',['AVIMMessagePatchEventArgs',['../classLeanCloud_1_1Realtime_1_1AVIMMessagePatchEventArgs.html#a778b48c99b6e78a7aa82f1ae166d2aa8',1,'LeanCloud::Realtime::AVIMMessagePatchEventArgs']]],
  ['avimmessagequery',['AVIMMessageQuery',['../classLeanCloud_1_1Realtime_1_1AVIMMessageQuery.html',1,'LeanCloud::Realtime']]],
  ['avimmessagequery',['AVIMMessageQuery',['../classLeanCloud_1_1Realtime_1_1AVIMMessageQuery.html#ac07d6df1e7f7a181412293306a781cda',1,'LeanCloud::Realtime::AVIMMessageQuery']]],
  ['avimnotice',['AVIMNotice',['../classLeanCloud_1_1Realtime_1_1AVIMNotice.html',1,'LeanCloud::Realtime']]],
  ['avimnotice',['AVIMNotice',['../classLeanCloud_1_1Realtime_1_1AVIMNotice.html#a1bb0d505607cc1bfcc36035aeef1b3e0',1,'LeanCloud.Realtime.AVIMNotice.AVIMNotice()'],['../classLeanCloud_1_1Realtime_1_1AVIMNotice.html#ae1fab41e48927687e658cb73b54e0021',1,'LeanCloud.Realtime.AVIMNotice.AVIMNotice(IDictionary&lt; string, object &gt; estimatedData)']]],
  ['avimnotice_2ecs',['AVIMNotice.cs',['../AVIMNotice_8cs.html',1,'']]],
  ['avimoninvitedeventargs',['AVIMOnInvitedEventArgs',['../classLeanCloud_1_1Realtime_1_1AVIMOnInvitedEventArgs.html',1,'LeanCloud::Realtime']]],
  ['avimonkickedeventargs',['AVIMOnKickedEventArgs',['../classLeanCloud_1_1Realtime_1_1AVIMOnKickedEventArgs.html',1,'LeanCloud::Realtime']]],
  ['avimonmemberschangedeventargs',['AVIMOnMembersChangedEventArgs',['../classLeanCloud_1_1Realtime_1_1AVIMOnMembersChangedEventArgs.html',1,'LeanCloud::Realtime']]],
  ['avimonmembersjoinedeventargs',['AVIMOnMembersJoinedEventArgs',['../classLeanCloud_1_1Realtime_1_1AVIMOnMembersJoinedEventArgs.html',1,'LeanCloud::Realtime']]],
  ['avimonmemberslefteventargs',['AVIMOnMembersLeftEventArgs',['../classLeanCloud_1_1Realtime_1_1AVIMOnMembersLeftEventArgs.html',1,'LeanCloud::Realtime']]],
  ['avimprotocol_2ecs',['AVIMProtocol.cs',['../AVIMProtocol_8cs.html',1,'']]],
  ['avimrecalledmessage',['AVIMRecalledMessage',['../classLeanCloud_1_1Realtime_1_1AVIMRecalledMessage.html',1,'LeanCloud::Realtime']]],
  ['avimrecalledmessage_2ecs',['AVIMRecalledMessage.cs',['../AVIMRecalledMessage_8cs.html',1,'']]],
  ['avimreconnectedeventargs',['AVIMReconnectedEventArgs',['../classLeanCloud_1_1Realtime_1_1AVIMReconnectedEventArgs.html',1,'LeanCloud::Realtime']]],
  ['avimreconnectfailedargs',['AVIMReconnectFailedArgs',['../classLeanCloud_1_1Realtime_1_1AVIMReconnectFailedArgs.html',1,'LeanCloud::Realtime']]],
  ['avimreconnectingeventargs',['AVIMReconnectingEventArgs',['../classLeanCloud_1_1Realtime_1_1AVIMReconnectingEventArgs.html',1,'LeanCloud::Realtime']]],
  ['avimreconnectoptions',['AVIMReconnectOptions',['../structLeanCloud_1_1Realtime_1_1AVRealtime_1_1AVIMReconnectOptions.html',1,'LeanCloud::Realtime::AVRealtime']]],
  ['avimsendoptions',['AVIMSendOptions',['../structLeanCloud_1_1Realtime_1_1AVIMSendOptions.html',1,'LeanCloud::Realtime']]],
  ['avimsessionclosedeventargs',['AVIMSessionClosedEventArgs',['../classLeanCloud_1_1Realtime_1_1AVIMSessionClosedEventArgs.html',1,'LeanCloud::Realtime']]],
  ['avimsignature',['AVIMSignature',['../classLeanCloud_1_1Realtime_1_1AVIMSignature.html',1,'LeanCloud::Realtime']]],
  ['avimsignature',['AVIMSignature',['../classLeanCloud_1_1Realtime_1_1AVIMSignature.html#a3ebdd4d5d2c8719e5d7bcde388b187ff',1,'LeanCloud::Realtime::AVIMSignature']]],
  ['avimsignature_2ecs',['AVIMSignature.cs',['../AVIMSignature_8cs.html',1,'']]],
  ['avimtemporaryconversation',['AVIMTemporaryConversation',['../classLeanCloud_1_1Realtime_1_1AVIMTemporaryConversation.html',1,'LeanCloud::Realtime']]],
  ['avimtemporaryconversation_2ecs',['AVIMTemporaryConversation.cs',['../AVIMTemporaryConversation_8cs.html',1,'']]],
  ['avimtextmessage',['AVIMTextMessage',['../classLeanCloud_1_1Realtime_1_1AVIMTextMessage.html',1,'LeanCloud::Realtime']]],
  ['avimtextmessage',['AVIMTextMessage',['../classLeanCloud_1_1Realtime_1_1AVIMTextMessage.html#a02bfd0497c13dc6a591ab902686e08c3',1,'LeanCloud.Realtime.AVIMTextMessage.AVIMTextMessage()'],['../classLeanCloud_1_1Realtime_1_1AVIMTextMessage.html#ab729252037d7a54cf16897819ea91a6f',1,'LeanCloud.Realtime.AVIMTextMessage.AVIMTextMessage(string textContent)']]],
  ['avimtextmessage_2ecs',['AVIMTextMessage.cs',['../AVIMTextMessage_8cs.html',1,'']]],
  ['avimtextmessageeventargs',['AVIMTextMessageEventArgs',['../classLeanCloud_1_1Realtime_1_1AVIMTextMessageEventArgs.html',1,'LeanCloud::Realtime']]],
  ['avimtextmessageeventargs',['AVIMTextMessageEventArgs',['../classLeanCloud_1_1Realtime_1_1AVIMTextMessageEventArgs.html#ab680a45833618befeac8b47ef79654e4',1,'LeanCloud::Realtime::AVIMTextMessageEventArgs']]],
  ['avimtextmessagelistener',['AVIMTextMessageListener',['../classLeanCloud_1_1Realtime_1_1AVIMTextMessageListener.html#a15a7c77dc4743fa34fc2ab57581718c3',1,'LeanCloud.Realtime.AVIMTextMessageListener.AVIMTextMessageListener()'],['../classLeanCloud_1_1Realtime_1_1AVIMTextMessageListener.html#ae9b537e02d87a9dbcab0adfb70cd1d73',1,'LeanCloud.Realtime.AVIMTextMessageListener.AVIMTextMessageListener(Action&lt; AVIMTextMessage &gt; textMessageReceived)']]],
  ['avimtextmessagelistener',['AVIMTextMessageListener',['../classLeanCloud_1_1Realtime_1_1AVIMTextMessageListener.html',1,'LeanCloud::Realtime']]],
  ['avimtypedmessage',['AVIMTypedMessage',['../classLeanCloud_1_1Realtime_1_1AVIMTypedMessage.html#acba427778dc7a7d17729d9630d6d376b',1,'LeanCloud::Realtime::AVIMTypedMessage']]],
  ['avimtypedmessage',['AVIMTypedMessage',['../classLeanCloud_1_1Realtime_1_1AVIMTypedMessage.html',1,'LeanCloud::Realtime']]],
  ['avimtypedmessage_2ecs',['AVIMTypedMessage.cs',['../AVIMTypedMessage_8cs.html',1,'']]],
  ['avimtypedmessagetypeintattribute',['AVIMTypedMessageTypeIntAttribute',['../classLeanCloud_1_1Realtime_1_1AVIMTypedMessageTypeIntAttribute.html',1,'LeanCloud::Realtime']]],
  ['avimtypedmessagetypeintattribute',['AVIMTypedMessageTypeIntAttribute',['../classLeanCloud_1_1Realtime_1_1AVIMTypedMessageTypeIntAttribute.html#a8fa2fab107450d0b34cc518935cf4d62',1,'LeanCloud::Realtime::AVIMTypedMessageTypeIntAttribute']]],
  ['avimtypedmessagetypeintattribute_2ecs',['AVIMTypedMessageTypeIntAttribute.cs',['../AVIMTypedMessageTypeIntAttribute_8cs.html',1,'']]],
  ['avimvideomessage',['AVIMVideoMessage',['../classLeanCloud_1_1Realtime_1_1AVIMVideoMessage.html',1,'LeanCloud::Realtime']]],
  ['avincrementoperation',['AVIncrementOperation',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVIncrementOperation.html',1,'LeanCloud::Storage::Internal']]],
  ['avincrementoperation',['AVIncrementOperation',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVIncrementOperation.html#af5c590d5cba9c66f3fc0d4c2003fab26',1,'LeanCloud::Storage::Internal::AVIncrementOperation']]],
  ['avincrementoperation_2ecs',['AVIncrementOperation.cs',['../AVIncrementOperation_8cs.html',1,'']]],
  ['avinitializebehaviour',['AVInitializeBehaviour',['../classLeanCloud_1_1AVInitializeBehaviour.html',1,'LeanCloud']]],
  ['avinitializebehaviour_2ecs',['AVInitializeBehaviour.cs',['../AVInitializeBehaviour_8cs.html',1,'']]],
  ['avleaderboard',['AVLeaderboard',['../classLeanCloud_1_1AVLeaderboard.html',1,'LeanCloud']]],
  ['avleaderboard_2ecs',['AVLeaderboard.cs',['../AVLeaderboard_8cs.html',1,'']]],
  ['avleaderboardarchive',['AVLeaderboardArchive',['../classLeanCloud_1_1AVLeaderboardArchive.html',1,'LeanCloud']]],
  ['avleaderboardarchive_2ecs',['AVLeaderboardArchive.cs',['../AVLeaderboardArchive_8cs.html',1,'']]],
  ['avleaderboardorder',['AVLeaderboardOrder',['../namespaceLeanCloud.html#a4b214e07f71915b0d9376ef4f2e839a0',1,'LeanCloud']]],
  ['avleaderboardupdatestrategy',['AVLeaderboardUpdateStrategy',['../namespaceLeanCloud.html#a44f72b620469a9fe4d10330c47b19c80',1,'LeanCloud']]],
  ['avleaderboardversionchangeinterval',['AVLeaderboardVersionChangeInterval',['../namespaceLeanCloud.html#ac2afca7d204b84e4ae71b0264e3eacfb',1,'LeanCloud']]],
  ['avlivequery',['AVLiveQuery',['../classLeanCloud_1_1LiveQuery_1_1AVLiveQuery.html',1,'LeanCloud::LiveQuery']]],
  ['avlivequery',['AVLiveQuery',['../classLeanCloud_1_1LiveQuery_1_1AVLiveQuery_3_01T_01_4.html#a226368d33174579f4cf57f7163dad82a',1,'LeanCloud::LiveQuery::AVLiveQuery&lt; T &gt;']]],
  ['avlivequery_2ecs',['AVLiveQuery.cs',['../AVLiveQuery_8cs.html',1,'']]],
  ['avlivequery_3c_20t_20_3e',['AVLiveQuery&lt; T &gt;',['../classLeanCloud_1_1LiveQuery_1_1AVLiveQuery_3_01T_01_4.html',1,'LeanCloud::LiveQuery']]],
  ['avlivequeryeventargs_2ecs',['AVLiveQueryEventArgs.cs',['../AVLiveQueryEventArgs_8cs.html',1,'']]],
  ['avlivequeryeventargs_3c_20t_20_3e',['AVLiveQueryEventArgs&lt; T &gt;',['../classLeanCloud_1_1LiveQuery_1_1AVLiveQueryEventArgs_3_01T_01_4.html',1,'LeanCloud::LiveQuery']]],
  ['avlivequeryextensions',['AVLiveQueryExtensions',['../classLeanCloud_1_1LiveQuery_1_1AVLiveQueryExtensions.html',1,'LeanCloud::LiveQuery']]],
  ['avlivequeryextensions_2ecs',['AVLiveQueryExtensions.cs',['../AVLiveQueryExtensions_8cs.html',1,'']]],
  ['avobject',['AVObject',['../classLeanCloud_1_1AVObject.html',1,'LeanCloud']]],
  ['avobject',['AVObject',['../classLeanCloud_1_1AVObject.html#a4262139bd87638aa19f86ac63e8826d7',1,'LeanCloud.AVObject.AVObject()'],['../classLeanCloud_1_1AVObject.html#a4dfad9998d7dafa7804402ad64fb3e68',1,'LeanCloud.AVObject.AVObject(string className)']]],
  ['avobject_2ecs',['AVObject.cs',['../AVObject_8cs.html',1,'']]],
  ['avobjectcoder',['AVObjectCoder',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVObjectCoder.html',1,'LeanCloud::Storage::Internal']]],
  ['avobjectcoder_2ecs',['AVObjectCoder.cs',['../AVObjectCoder_8cs.html',1,'']]],
  ['avobjectcomparer',['AVObjectComparer',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVFieldOperations.html#ab511a27427ee9accd41ce2a781ccf720',1,'LeanCloud::Storage::Internal::AVFieldOperations']]],
  ['avobjectcontroller',['AVObjectController',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVObjectController.html',1,'LeanCloud::Storage::Internal']]],
  ['avobjectcontroller',['AVObjectController',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVObjectController.html#a5a499828182789796d9da7fab0503ef1',1,'LeanCloud::Storage::Internal::AVObjectController']]],
  ['avobjectcontroller_2ecs',['AVObjectController.cs',['../AVObjectController_8cs.html',1,'']]],
  ['avobjectdeserializer',['AVObjectDeserializer',['../classLeanCloud_1_1AVObjectRPCCloudFunction_3_01R_01_4.html#a26f5a13e44f300616ce185f6fecc99a5',1,'LeanCloud::AVObjectRPCCloudFunction&lt; R &gt;']]],
  ['avobjectextensions',['AVObjectExtensions',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVObjectExtensions.html',1,'LeanCloud::Storage::Internal']]],
  ['avobjectextensions_2ecs',['AVObjectExtensions.cs',['../AVObjectExtensions_8cs.html',1,'']]],
  ['avobjectidcomparer',['AVObjectIdComparer',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVObjectIdComparer.html',1,'LeanCloud::Storage::Internal']]],
  ['avobjectlistdeserializer',['AVObjectListDeserializer',['../classLeanCloud_1_1AVObjectListRPCCloudFunction_3_01R_01_4.html#a5a3be2cab6ac6b8e487a57b2c44d42b7',1,'LeanCloud::AVObjectListRPCCloudFunction&lt; R &gt;']]],
  ['avobjectlistrpccloudfunction',['AVObjectListRPCCloudFunction',['../classLeanCloud_1_1AVObjectListRPCCloudFunction_3_01R_01_4.html#abc673b0bcf1572a6c87bd8180d42e167',1,'LeanCloud::AVObjectListRPCCloudFunction&lt; R &gt;']]],
  ['avobjectlistrpccloudfunction',['AVObjectListRPCCloudFunction',['../classLeanCloud_1_1AVObjectListRPCCloudFunction.html',1,'LeanCloud']]],
  ['avobjectlistrpccloudfunction_3c_20r_20_3e',['AVObjectListRPCCloudFunction&lt; R &gt;',['../classLeanCloud_1_1AVObjectListRPCCloudFunction_3_01R_01_4.html',1,'LeanCloud']]],
  ['avobjectrpccloudfunction',['AVObjectRPCCloudFunction',['../classLeanCloud_1_1AVObjectRPCCloudFunction.html',1,'LeanCloud']]],
  ['avobjectrpccloudfunction',['AVObjectRPCCloudFunction',['../classLeanCloud_1_1AVObjectRPCCloudFunction_3_01R_01_4.html#a936d3c5c62dc27dae22d75352515f266',1,'LeanCloud::AVObjectRPCCloudFunction&lt; R &gt;']]],
  ['avobjectrpccloudfunction_3c_20r_20_3e',['AVObjectRPCCloudFunction&lt; R &gt;',['../classLeanCloud_1_1AVObjectRPCCloudFunction_3_01R_01_4.html',1,'LeanCloud']]],
  ['avplugins',['AVPlugins',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVPlugins.html',1,'LeanCloud::Storage::Internal']]],
  ['avquery',['AVQuery',['../classLeanCloud_1_1AVQuery_3_01T_01_4.html#a887a3efa93607fd555eae2e1d56406a1',1,'LeanCloud.AVQuery&lt; T &gt;.AVQuery()'],['../classLeanCloud_1_1AVQuery_3_01T_01_4.html#aa0619c65870162e88a3d6513f2038780',1,'LeanCloud.AVQuery&lt; T &gt;.AVQuery(string className)']]],
  ['avquery_2ecs',['AVQuery.cs',['../AVQuery_8cs.html',1,'']]],
  ['avquery_3c_20t_20_3e',['AVQuery&lt; T &gt;',['../classLeanCloud_1_1AVQuery_3_01T_01_4.html',1,'LeanCloud']]],
  ['avquerybase_3c_20t_20_3e',['AVQueryBase&lt; T &gt;',['../classLeanCloud_1_1AVQueryBase_3_01T_01_4.html',1,'LeanCloud']]],
  ['avquerycontroller_2ecs',['AVQueryController.cs',['../AVQueryController_8cs.html',1,'']]],
  ['avqueryextensions',['AVQueryExtensions',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVQueryExtensions.html',1,'LeanCloud::Storage::Internal']]],
  ['avqueryextensions',['AVQueryExtensions',['../classLeanCloud_1_1AVQueryExtensions.html',1,'LeanCloud']]],
  ['avqueryextensions_2ecs',['AVQueryExtensions.cs',['../Public_2AVQueryExtensions_8cs.html',1,'']]],
  ['avqueryextensions_2ecs',['AVQueryExtensions.cs',['../Internal_2Utilities_2AVQueryExtensions_8cs.html',1,'']]],
  ['avquerypair',['AVQueryPair',['../classLeanCloud_1_1AVQueryPair_3_01S_00_01T_01_4.html#a9daba25e39146c21931f699e7d5c0ae3',1,'LeanCloud.AVQueryPair&lt; S, T &gt;.AVQueryPair()'],['../classLeanCloud_1_1AVQueryPair_3_01S_00_01T_01_4.html#af8d0ab70f05059e0b694bed1c69abaec',1,'LeanCloud.AVQueryPair&lt; S, T &gt;.AVQueryPair(AVQueryPair&lt; S, T &gt; source, IDictionary&lt; string, object &gt; where=null, IEnumerable&lt; string &gt; replacementOrderBy=null, IEnumerable&lt; string &gt; thenBy=null, int?skip=null, int?limit=null, IEnumerable&lt; string &gt; includes=null, IEnumerable&lt; string &gt; selectedKeys=null, String redirectClassNameForKey=null)'],['../classLeanCloud_1_1AVQueryPair_3_01S_00_01T_01_4.html#a1a9db4e164cfb78d1ccc54ce06e6fa55',1,'LeanCloud.AVQueryPair&lt; S, T &gt;.AVQueryPair(string className)']]],
  ['avquerypair_3c_20s_2c_20t_20_3e',['AVQueryPair&lt; S, T &gt;',['../classLeanCloud_1_1AVQueryPair_3_01S_00_01T_01_4.html',1,'LeanCloud']]],
  ['avranking',['AVRanking',['../classLeanCloud_1_1AVRanking.html',1,'LeanCloud']]],
  ['avranking_2ecs',['AVRanking.cs',['../AVRanking_8cs.html',1,'']]],
  ['avrealtime',['AVRealtime',['../classLeanCloud_1_1Realtime_1_1AVRealtime.html#aa013d9f019aafcb527dae73b1d0a46bd',1,'LeanCloud.Realtime.AVRealtime.AVRealtime(Configuration config)'],['../classLeanCloud_1_1Realtime_1_1AVRealtime.html#a60716823997776a07102c09f7c9ee784',1,'LeanCloud.Realtime.AVRealtime.AVRealtime(string applicationId, string applicationKey)']]],
  ['avrealtime',['AVRealtime',['../classLeanCloud_1_1Realtime_1_1AVRealtime.html',1,'LeanCloud::Realtime']]],
  ['avrealtime_2ecs',['AVRealtime.cs',['../AVRealtime_8cs.html',1,'']]],
  ['avrealtimebehavior',['AVRealtimeBehavior',['../classLeanCloud_1_1Realtime_1_1AVRealtimeBehavior.html',1,'LeanCloud::Realtime']]],
  ['avrealtimebehavior_2ecs',['AVRealtimeBehavior.cs',['../AVRealtimeBehavior_8cs.html',1,'']]],
  ['avregion',['AVRegion',['../structLeanCloud_1_1AVClient_1_1Configuration.html#a47203687b8eee8aa26318afcdd86ab19',1,'LeanCloud::AVClient::Configuration']]],
  ['avrelation_2ecs',['AVRelation.cs',['../AVRelation_8cs.html',1,'']]],
  ['avrelation_3c_20t_20_3e',['AVRelation&lt; T &gt;',['../classLeanCloud_1_1AVRelation_3_01T_01_4.html',1,'LeanCloud']]],
  ['avrelationbase',['AVRelationBase',['../classLeanCloud_1_1AVRelationBase.html',1,'LeanCloud']]],
  ['avrelationextensions',['AVRelationExtensions',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVRelationExtensions.html',1,'LeanCloud::Storage::Internal']]],
  ['avrelationextensions_2ecs',['AVRelationExtensions.cs',['../AVRelationExtensions_8cs.html',1,'']]],
  ['avrelationoperation',['AVRelationOperation',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVRelationOperation.html',1,'LeanCloud::Storage::Internal']]],
  ['avrelationoperation',['AVRelationOperation',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVRelationOperation.html#a06f0bd673126f76243dfa5cb38bdbe9d',1,'LeanCloud::Storage::Internal::AVRelationOperation']]],
  ['avrelationoperation_2ecs',['AVRelationOperation.cs',['../AVRelationOperation_8cs.html',1,'']]],
  ['avremoveoperation',['AVRemoveOperation',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVRemoveOperation.html#ad43cfb4b7c0c2c8f073e481ce7ec55e5',1,'LeanCloud::Storage::Internal::AVRemoveOperation']]],
  ['avremoveoperation',['AVRemoveOperation',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVRemoveOperation.html',1,'LeanCloud::Storage::Internal']]],
  ['avremoveoperation_2ecs',['AVRemoveOperation.cs',['../AVRemoveOperation_8cs.html',1,'']]],
  ['avrole',['AVRole',['../classLeanCloud_1_1AVRole.html#a47f9525a039767305bc059af7fcf483f',1,'LeanCloud.AVRole.AVRole()'],['../classLeanCloud_1_1AVRole.html#a1b530932086f0b5a87f5418688fbac26',1,'LeanCloud.AVRole.AVRole(string name, AVACL acl)']]],
  ['avrole',['AVRole',['../classLeanCloud_1_1AVRole.html',1,'LeanCloud']]],
  ['avrole_2ecs',['AVRole.cs',['../AVRole_8cs.html',1,'']]],
  ['avroutercontroller_2ecs',['AVRouterController.cs',['../AVRouterController_8cs.html',1,'']]],
  ['avrpccloudfunctionbase',['AVRPCCloudFunctionBase',['../classLeanCloud_1_1AVRPCCloudFunctionBase_3_01P_00_01R_01_4.html#a1214607fa8255c1c93be56458ef10e0c',1,'LeanCloud.AVRPCCloudFunctionBase&lt; P, R &gt;.AVRPCCloudFunctionBase()'],['../classLeanCloud_1_1AVRPCCloudFunctionBase_3_01P_00_01R_01_4.html#affe03cabed5e624714d893cc89937dcb',1,'LeanCloud.AVRPCCloudFunctionBase&lt; P, R &gt;.AVRPCCloudFunctionBase(bool noneParameters)']]],
  ['avrpccloudfunctionbase_3c_20p_2c_20r_20_3e',['AVRPCCloudFunctionBase&lt; P, R &gt;',['../classLeanCloud_1_1AVRPCCloudFunctionBase_3_01P_00_01R_01_4.html',1,'LeanCloud']]],
  ['avrpcdeserialize_3c_20r_20_3e',['AVRPCDeserialize&lt; R &gt;',['../classLeanCloud_1_1AVRPCCloudFunctionBase_3_01P_00_01R_01_4.html#a16bb5d396f043b83dfe7387f3fd8c317',1,'LeanCloud::AVRPCCloudFunctionBase&lt; P, R &gt;']]],
  ['avrpcserialize_3c_20p_20_3e',['AVRPCSerialize&lt; P &gt;',['../classLeanCloud_1_1AVRPCCloudFunctionBase_3_01P_00_01R_01_4.html#a652c1f3f4cf5f3a8cab65897edc624be',1,'LeanCloud::AVRPCCloudFunctionBase&lt; P, R &gt;']]],
  ['avsession',['AVSession',['../classLeanCloud_1_1AVSession.html',1,'LeanCloud']]],
  ['avsession_2ecs',['AVSession.cs',['../AVSession_8cs.html',1,'']]],
  ['avsessioncontroller',['AVSessionController',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVSessionController.html#a0e45ff70671d36d558c3bf2489934899',1,'LeanCloud::Storage::Internal::AVSessionController']]],
  ['avsessioncontroller',['AVSessionController',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVSessionController.html',1,'LeanCloud::Storage::Internal']]],
  ['avsessioncontroller_2ecs',['AVSessionController.cs',['../AVSessionController_8cs.html',1,'']]],
  ['avsessionextensions',['AVSessionExtensions',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVSessionExtensions.html',1,'LeanCloud::Storage::Internal']]],
  ['avsessionextensions_2ecs',['AVSessionExtensions.cs',['../AVSessionExtensions_8cs.html',1,'']]],
  ['avsetoperation',['AVSetOperation',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVSetOperation.html',1,'LeanCloud::Storage::Internal']]],
  ['avsetoperation',['AVSetOperation',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVSetOperation.html#a9dca24be969958f813b3e7b13ef0ee60',1,'LeanCloud::Storage::Internal::AVSetOperation']]],
  ['avsetoperation_2ecs',['AVSetOperation.cs',['../AVSetOperation_8cs.html',1,'']]],
  ['avstatistic',['AVStatistic',['../classLeanCloud_1_1AVStatistic.html',1,'LeanCloud']]],
  ['avstatistic',['AVStatistic',['../classLeanCloud_1_1AVStatistic.html#aeb595408d5130cd29739d75aa72ea2af',1,'LeanCloud::AVStatistic']]],
  ['avstatistic_2ecs',['AVStatistic.cs',['../AVStatistic_8cs.html',1,'']]],
  ['avstatus',['AVStatus',['../classLeanCloud_1_1AVStatus.html',1,'LeanCloud']]],
  ['avstatus_2ecs',['AVStatus.cs',['../AVStatus_8cs.html',1,'']]],
  ['avtimer',['AVTimer',['../classLeanCloud_1_1Realtime_1_1Internal_1_1AVTimer.html#a9a7fdab3306fb9b7d0083f6fe614e449',1,'LeanCloud.Realtime.Internal.AVTimer.AVTimer()'],['../classLeanCloud_1_1Realtime_1_1Internal_1_1AVTimer.html#a9a7fdab3306fb9b7d0083f6fe614e449',1,'LeanCloud.Realtime.Internal.AVTimer.AVTimer()']]],
  ['avtimer',['AVTimer',['../classLeanCloud_1_1Realtime_1_1Internal_1_1AVTimer.html',1,'LeanCloud::Realtime::Internal']]],
  ['avtimer_2eportable_2ecs',['AVTimer.Portable.cs',['../AVTimer_8Portable_8cs.html',1,'']]],
  ['avtimer_2eunity_2ecs',['AVTimer.Unity.cs',['../AVTimer_8Unity_8cs.html',1,'']]],
  ['avuploadprogresseventargs',['AVUploadProgressEventArgs',['../classLeanCloud_1_1AVUploadProgressEventArgs.html#ae1112d002af83c25eae06ff762d86c5f',1,'LeanCloud::AVUploadProgressEventArgs']]],
  ['avuploadprogresseventargs',['AVUploadProgressEventArgs',['../classLeanCloud_1_1AVUploadProgressEventArgs.html',1,'LeanCloud']]],
  ['avuploadprogresseventargs_2ecs',['AVUploadProgressEventArgs.cs',['../AVUploadProgressEventArgs_8cs.html',1,'']]],
  ['avuser',['AVUser',['../classLeanCloud_1_1AVUser.html',1,'LeanCloud']]],
  ['avuser_2ecs',['AVUser.cs',['../AVUser_8cs.html',1,'']]],
  ['avuserauthdataloginoption',['AVUserAuthDataLogInOption',['../classLeanCloud_1_1AVUserAuthDataLogInOption.html#acb8dc8ec01f8ebaf07370948c1c89617',1,'LeanCloud::AVUserAuthDataLogInOption']]],
  ['avuserauthdataloginoption',['AVUserAuthDataLogInOption',['../classLeanCloud_1_1AVUserAuthDataLogInOption.html',1,'LeanCloud']]],
  ['avuserauthdataloginoption_2ecs',['AVUserAuthDataLogInOption.cs',['../AVUserAuthDataLogInOption_8cs.html',1,'']]],
  ['avusercontroller',['AVUserController',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVUserController.html#a4fd766c5149b72a7e74736a476eda374',1,'LeanCloud::Storage::Internal::AVUserController']]],
  ['avusercontroller',['AVUserController',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVUserController.html',1,'LeanCloud::Storage::Internal']]],
  ['avusercontroller_2ecs',['AVUserController.cs',['../AVUserController_8cs.html',1,'']]],
  ['avuserextensions',['AVUserExtensions',['../classLeanCloud_1_1Storage_1_1Internal_1_1AVUserExtensions.html',1,'LeanCloud::Storage::Internal']]],
  ['avuserextensions_2ecs',['AVUserExtensions.cs',['../AVUserExtensions_8cs.html',1,'']]],
  ['awss3filecontroller_2ecs',['AWSS3FileController.cs',['../AWSS3FileController_8cs.html',1,'']]]
];
