var searchData=
[
  ['iapproutercontroller',['IAppRouterController',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IAppRouterController.html',1,'LeanCloud::Storage::Internal']]],
  ['iavauthenticationprovider',['IAVAuthenticationProvider',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IAVAuthenticationProvider.html',1,'LeanCloud::Storage::Internal']]],
  ['iavcloudcodecontroller',['IAVCloudCodeController',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IAVCloudCodeController.html',1,'LeanCloud::Storage::Internal']]],
  ['iavcommandrunner',['IAVCommandRunner',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IAVCommandRunner.html',1,'LeanCloud::Storage::Internal']]],
  ['iavconfigcontroller',['IAVConfigController',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IAVConfigController.html',1,'LeanCloud::Storage::Internal']]],
  ['iavcoreplugins',['IAVCorePlugins',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IAVCorePlugins.html',1,'LeanCloud::Storage::Internal']]],
  ['iavcurrentconfigcontroller',['IAVCurrentConfigController',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IAVCurrentConfigController.html',1,'LeanCloud::Storage::Internal']]],
  ['iavcurrentusercontroller',['IAVCurrentUserController',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IAVCurrentUserController.html',1,'LeanCloud::Storage::Internal']]],
  ['iavfieldoperation',['IAVFieldOperation',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IAVFieldOperation.html',1,'LeanCloud::Storage::Internal']]],
  ['iavfilecontroller',['IAVFileController',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IAVFileController.html',1,'LeanCloud::Storage::Internal']]],
  ['iavimcommandrunner',['IAVIMCommandRunner',['../interfaceLeanCloud_1_1Realtime_1_1Internal_1_1IAVIMCommandRunner.html',1,'LeanCloud::Realtime::Internal']]],
  ['iavimconversatiobuilder',['IAVIMConversatioBuilder',['../interfaceLeanCloud_1_1Realtime_1_1IAVIMConversatioBuilder.html',1,'LeanCloud::Realtime']]],
  ['iavimlistener',['IAVIMListener',['../interfaceLeanCloud_1_1Realtime_1_1IAVIMListener.html',1,'LeanCloud::Realtime']]],
  ['iavimmessage',['IAVIMMessage',['../interfaceLeanCloud_1_1Realtime_1_1IAVIMMessage.html',1,'LeanCloud::Realtime']]],
  ['iavimnotice',['IAVIMNotice',['../interfaceLeanCloud_1_1Realtime_1_1IAVIMNotice.html',1,'LeanCloud::Realtime']]],
  ['iavimplatformhooks',['IAVIMPlatformHooks',['../interfaceLeanCloud_1_1Realtime_1_1Internal_1_1IAVIMPlatformHooks.html',1,'LeanCloud::Realtime::Internal']]],
  ['iavobject',['IAVObject',['../interfaceLeanCloud_1_1IAVObject.html',1,'LeanCloud']]],
  ['iavobjectcontroller',['IAVObjectController',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IAVObjectController.html',1,'LeanCloud::Storage::Internal']]],
  ['iavobjectcurrentcontroller_3c_20t_20_3e',['IAVObjectCurrentController&lt; T &gt;',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IAVObjectCurrentController_3_01T_01_4.html',1,'LeanCloud::Storage::Internal']]],
  ['iavquery',['IAVQuery',['../interfaceLeanCloud_1_1IAVQuery.html',1,'LeanCloud']]],
  ['iavquerycontroller',['IAVQueryController',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IAVQueryController.html',1,'LeanCloud::Storage::Internal']]],
  ['iavroutercontroller',['IAVRouterController',['../interfaceLeanCloud_1_1Realtime_1_1Internal_1_1IAVRouterController.html',1,'LeanCloud::Realtime::Internal']]],
  ['iavsessioncontroller',['IAVSessionController',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IAVSessionController.html',1,'LeanCloud::Storage::Internal']]],
  ['iavtimer',['IAVTimer',['../interfaceLeanCloud_1_1Realtime_1_1Internal_1_1IAVTimer.html',1,'LeanCloud::Realtime::Internal']]],
  ['iavusercontroller',['IAVUserController',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IAVUserController.html',1,'LeanCloud::Storage::Internal']]],
  ['identityequalitycomparer_3c_20t_20_3e',['IdentityEqualityComparer&lt; T &gt;',['../classLeanCloud_1_1Storage_1_1Internal_1_1IdentityEqualityComparer_3_01T_01_4.html',1,'LeanCloud::Storage::Internal']]],
  ['ifreestylemessageclassingcontroller',['IFreeStyleMessageClassingController',['../interfaceLeanCloud_1_1Realtime_1_1Internal_1_1IFreeStyleMessageClassingController.html',1,'LeanCloud::Realtime::Internal']]],
  ['ihttpclient',['IHttpClient',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IHttpClient.html',1,'LeanCloud::Storage::Internal']]],
  ['iinstallationidcontroller',['IInstallationIdController',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IInstallationIdController.html',1,'LeanCloud::Storage::Internal']]],
  ['ijsonconvertible',['IJsonConvertible',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IJsonConvertible.html',1,'LeanCloud::Storage::Internal']]],
  ['inotifycollectionpropertyupdated',['INotifyCollectionPropertyUpdated',['../interfaceLeanCloud_1_1INotifyCollectionPropertyUpdated.html',1,'LeanCloud']]],
  ['inotifypropertyupdated',['INotifyPropertyUpdated',['../interfaceLeanCloud_1_1INotifyPropertyUpdated.html',1,'LeanCloud']]],
  ['installationidcontroller',['InstallationIdController',['../classLeanCloud_1_1Storage_1_1Internal_1_1InstallationIdController.html',1,'LeanCloud::Storage::Internal']]],
  ['internalextensions',['InternalExtensions',['../classLeanCloud_1_1Storage_1_1Internal_1_1InternalExtensions.html',1,'LeanCloud::Storage::Internal']]],
  ['iobjectstate',['IObjectState',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IObjectState.html',1,'LeanCloud::Storage::Internal']]],
  ['iobjectsubclassingcontroller',['IObjectSubclassingController',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IObjectSubclassingController.html',1,'LeanCloud::Storage::Internal']]],
  ['isignaturefactory',['ISignatureFactory',['../interfaceLeanCloud_1_1Realtime_1_1ISignatureFactory.html',1,'LeanCloud::Realtime']]],
  ['isqlstorage',['ISQLStorage',['../interfaceLeanCloud_1_1Realtime_1_1ISQLStorage.html',1,'LeanCloud::Realtime']]],
  ['istoragecontroller',['IStorageController',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IStorageController.html',1,'LeanCloud::Storage::Internal']]],
  ['istoragedictionary_3c_20tkey_2c_20tvalue_20_3e',['IStorageDictionary&lt; TKey, TValue &gt;',['../interfaceLeanCloud_1_1Storage_1_1Internal_1_1IStorageDictionary_3_01TKey_00_01TValue_01_4.html',1,'LeanCloud::Storage::Internal']]],
  ['iwebsocketclient',['IWebSocketClient',['../interfaceLeanCloud_1_1Realtime_1_1Internal_1_1IWebSocketClient.html',1,'LeanCloud::Realtime::Internal']]]
];
