name: .NET

on:
  push:
    tags:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - run: sh ./script/package.sh
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_PATH: release/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Doc
      uses: mattnotmitt/doxygen-action@v1
      with:
          working-directory: './'
          doxyfile-path: 'docs/html'
    - name: Deploy doc
      run: bash ./script/deploy.sh
